### ISSUE TITLE
Word Cloud not working, figure out a way to get it to work

### ISSUE THREAD

**Issue by IshaanShettigar** [vivek-698/Chaos-to-Clarity#6]
The code is located in `word_cloud.py` that is in the `scripts` folder. For some reason I am getting this error. I do not know how to fix it. 
I tried a solution mentioned by chatGPT and a StackOverflow article but nothing worked. I believe there has to be a simple solution for this. 

This is the error I am getting
```
C:\Users\Ishaan\Documents\5th Semester\Hallothon\Chaos-to-Clarity> python3 scripts/word_cloud.py
Traceback (most recent call last):
  File "C:\Users\Ishaan\Documents\5th Semester\Hallothon\Chaos-to-Clarity\scripts\word_cloud.py", line 11, in <module>
    positive_wordcloud = WordCloud(
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wordcloud\wordcloud.py", line 639, in generate
    return self.generate_from_text(text)
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wordcloud\wordcloud.py", line 621, in generate_from_text
    self.generate_from_frequencies(words)
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wordcloud\wordcloud.py", line 508, in generate_from_frequencies
    box_size = draw.textsize(word, font=transposed_font)
AttributeError: 'ImageDraw' object has no attribute 'textsize'
(base) PS C:\Users\Ishaan\Documents\5th Semester\Hallothon\Chaos-to-Clarity>
```

**Comment by thedoctor095** [comment]
Hello,
I'd like to help on this.

**Comment by IshaanShettigar** [comment]
Amazing! I have assigned this issue to you.

**Comment by thedoctor095** [comment]
Issue addressed [here](https://github.com/vivek-698/Chaos-to-Clarity/pull/7).
